#!/usr/bin/env python3
"""Rebuild the ColdFire source consumed by Linked, or --check for drift.

The firmware builder accepts GNU-as units: the engine stays in C and its
compiler output is checked in beside it, as modules/euclid does.
"""
import pathlib
import re
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
# -fno-auto-inc-dec: GCC 16.2 combined a byte copy into `move.b (%a0)+,(%a0,%d1.l)`.
# The CPU forms the destination after the source's increment, so every byte
# landed one address high; generate() refuses that shape as well.
FLAGS = ['-mcpu=5475', '-msoft-float', '-O2', '-ffreestanding', '-fno-builtin',
         '-fno-common', '-fno-jump-tables', '-fno-asynchronous-unwind-tables',
         '-fno-ident', '-fomit-frame-pointer', '-fno-tree-loop-distribute-patterns', '-fno-auto-inc-dec']


def generate():
    with tempfile.TemporaryDirectory() as td:
        asm = pathlib.Path(td) / 'turing.s'
        subprocess.run(['m68k-elf-gcc', *FLAGS, '-S', 'turing.c', '-o', str(asm)], cwd=HERE, check=True)
        code = asm.read_text()
        hazard = re.search(r'\((%a[0-7])\)\+,.*\1|-\((%a[0-7])\),.*\2', code)
        if hazard:
            sys.exit('generate.py: one register both auto-modified and addressed in one move: ' + hazard.group(0))
        return ('| Generated by generate.py beside it; edit turing.c / hooks.s.\n'
                + code + '\n' + (HERE / 'hooks.s').read_text())


if __name__ == '__main__':
    source = generate()
    dest = HERE / 'turing.s'
    if '--check' in sys.argv:
        if not dest.exists() or source != dest.read_text():
            sys.exit('turing.s is stale: run modules/turing-machine/generate.py')
        print('turing.s matches turing.c and hooks.s')
    else:
        dest.write_text(source)
