| Generated by generate.py beside it; edit turing.c / hooks.s.
#NO_APP
	.file	"turing.c"
	.text
	.align	2
	.globl	tm_track
	.type	tm_track, @function
tm_track:
	move.l %d2,-(%sp)
	moveq #8,%d2
	move.b 269161704,%d0
	move.b 269161705,%d1
	move.w %d1,%a0
	mvz.b %d0,%d1
	cmp.l %d1,%d2
	jcs .L4
	move.w %a0,%d1
	tst.b %d1
	jlt .L4
	move.l %a0,%d2
	eor.l %d2,%d0
	moveq #90,%d2
	mvz.b 269161706,%d1
	eor.l %d2,%d0
	mvz.b %d0,%d0
	cmp.l %d1,%d0
	jeq .L7
.L4:
	move.l (%sp)+,%d2
	clr.l %d0
	rts
.L7:
	mvz.b 269161704,%d0
	move.l (%sp)+,%d2
	rts
	.size	tm_track, .-tm_track
	.align	2
	.globl	tm_lock
	.type	tm_lock, @function
tm_lock:
	move.l %d2,-(%sp)
	moveq #8,%d2
	move.b 269161704,%d0
	move.b 269161705,%d1
	move.w %d1,%a0
	mvz.b %d0,%d1
	cmp.l %d1,%d2
	jcs .L11
	move.w %a0,%d1
	tst.b %d1
	jlt .L11
	move.l %a0,%d2
	eor.l %d2,%d0
	moveq #90,%d2
	mvz.b 269161706,%d1
	eor.l %d2,%d0
	mvz.b %d0,%d0
	cmp.l %d1,%d0
	jeq .L14
.L11:
	move.l (%sp)+,%d2
	moveq #64,%d0
	rts
.L14:
	mvz.b 269161705,%d0
	move.l (%sp)+,%d2
	rts
	.size	tm_lock, .-tm_lock
	.align	2
	.globl	tm_step
	.type	tm_step, @function
tm_step:
	lea (-24,%sp),%sp
	movem.l #1148,(%sp)
	move.l 28(%sp),%a2
	tst.b 6(%a2)
	jeq .L16
	move.w 4(%a2),%d0
	move.l (%a2),%a0
.L17:
	moveq #127,%d2
	moveq #13,%d5
	sub.l 32(%sp),%d2
	move.l %a0,%d1
	moveq #15,%d6
	lsl.l %d5,%d1
	move.l %a0,%d4
	lsl.l #8,%d2
	eor.l %d4,%d1
	move.l %d2,%d5
	mvz.w %d0,%d2
	lsr.l %d6,%d2
	moveq #127,%d6
	divu.l %d6,%d5
	moveq #17,%d6
	move.w %d2,%d3
	move.l %d5,%a1
	move.l %d1,%d5
	lsr.l %d6,%d5
	eor.l %d5,%d1
	move.l %d1,%d4
	lsl.l #5,%d4
	eor.l %d4,%d1
	move.l %d1,%d5
	mvz.b %d5,%d5
	move.l %d1,(%a2)
	cmp.l %d5,%a1
	jls .L18
	mov3q.l #1,%d3
	eor.l %d2,%d3
.L18:
	add.l %d0,%d0
	or.l %d3,%d0
	move.w %d0,4(%a2)
	movem.l (%sp),#1148
	mvz.b %d0,%d0
	lea (24,%sp),%sp
	rts
.L16:
	move.l #-1640531527,%d0
	moveq #13,%d3
	move.l 36(%sp),%d1
	addq.l #1,%d1
	muls.l %d0,%d1
	moveq #17,%d4
	moveq #1,%d2
	eor.l #1831565813,%d1
	move.b %d2,6(%a2)
	move.l %d1,%d0
	lsl.l %d3,%d0
	eor.l %d1,%d0
	move.l %d0,%d1
	lsr.l %d4,%d1
	eor.l %d1,%d0
	move.l %d0,%d1
	lsl.l #5,%d1
	eor.l %d1,%d0
	move.l %d0,%a0
	jra .L17
	.size	tm_step, .-tm_step
	.align	2
	.globl	tm_note
	.type	tm_note, @function
tm_note:
	subq.l #4,%sp
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	mov3q.l #7,%d0
	cmp.l 16(%sp),%d0
	jcc .L32
.L21:
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L32:
	move.b 269161704,%d1
	move.b 269161705,%d0
	moveq #8,%d3
	mvz.b %d1,%d2
	cmp.l %d2,%d3
	jcs .L21
	tst.b %d0
	jlt .L21
	eor.l %d0,%d1
	moveq #90,%d2
	mvz.b 269161706,%d0
	eor.l %d2,%d1
	mvz.b %d1,%d1
	cmp.l %d0,%d1
	jne .L21
	mvz.b 269161704,%d1
	move.l 16(%sp),%a0
	addq.l #1,%a0
	cmp.l %a0,%d1
	jne .L21
	move.l 20(%sp),%a0
	tst.b (%a0)
	jlt .L21
	move.b 269161704,%d1
	move.b 269161705,%d0
	mvz.b %d1,%d2
	move.w %d0,%a1
	cmp.l %d2,%d3
	jcs .L23
	tst.b %d0
	jlt .L23
	move.l %a1,%d3
	moveq #90,%d2
	eor.l %d3,%d1
	mvz.b 269161706,%d0
	eor.l %d2,%d1
	mvz.b %d1,%d1
	cmp.l %d0,%d1
	jne .L23
	move.l 16(%sp),%d3
	mvz.b 269161705,%d1
	move.l 16(%sp),-(%sp)
	lsl.l #3,%d3
	mvz.w #255,%d2
	move.l %d1,-(%sp)
	move.l %d3,%a0
	add.l #tm_states,%a0
	move.l %a0,-(%sp)
	jsr tm_step
	move.l 32(%sp),%a0
	lea (12,%sp),%sp
	mulu.w #24,%d0
	lea (4,%a0),%a1
	move.l %a1,8(%sp)
	move.l %d0,%d1
	divu.l %d2,%d1
	move.l %d1,%a1
.L28:
	mvs.b (%a0)+,%d1
	move.l %a1,%d0
	add.l %d1,%d0
	tst.l %d1
	jlt .L26
	moveq #127,%d1
	cmp.l %d0,%d1
	jge .L27
	mov3q.l #-1,%d0
.L27:
	move.b %d0,-1(%a0)
.L26:
	cmp.l 8(%sp),%a0
	jne .L28
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L23:
	move.l 16(%sp),%d3
	moveq #64,%d1
	move.l 16(%sp),-(%sp)
	move.l %d1,-(%sp)
	lsl.l #3,%d3
	mvz.w #255,%d2
	move.l %d3,%a0
	add.l #tm_states,%a0
	move.l %a0,-(%sp)
	jsr tm_step
	move.l 32(%sp),%a0
	lea (12,%sp),%sp
	mulu.w #24,%d0
	lea (4,%a0),%a1
	move.l %a1,8(%sp)
	move.l %d0,%d1
	divu.l %d2,%d1
	move.l %d1,%a1
	jra .L28
	.size	tm_note, .-tm_note
	.align	2
	.globl	tm_get_track
	.type	tm_get_track, @function
tm_get_track:
	move.l %d2,-(%sp)
	moveq #8,%d2
	move.b 269161704,%d0
	move.b 269161705,%d1
	move.w %d1,%a0
	mvz.b %d0,%d1
	cmp.l %d1,%d2
	jcs .L36
	move.w %a0,%d1
	tst.b %d1
	jlt .L36
	move.l %a0,%d2
	eor.l %d2,%d0
	moveq #90,%d2
	mvz.b 269161706,%d1
	eor.l %d2,%d0
	mvz.b %d0,%d0
	cmp.l %d1,%d0
	jeq .L39
.L36:
	move.l (%sp)+,%d2
	move.l #tm_track_names,%d0
	rts
.L39:
	mvz.b 269161704,%d0
	move.l (%sp)+,%d2
	lsl.l #2,%d0
	add.l #tm_track_names,%d0
	rts
	.size	tm_get_track, .-tm_get_track
	.align	2
	.globl	tm_get_lock
	.type	tm_get_lock, @function
tm_get_lock:
	lea (-12,%sp),%sp
	movem.l #28,(%sp)
	moveq #8,%d2
	move.b 269161704,%d0
	move.b 269161705,%d1
	move.w %d1,%a0
	mvz.b %d0,%d1
	cmp.l %d1,%d2
	jcs .L43
	move.w %a0,%d3
	tst.b %d3
	jlt .L43
	move.l %a0,%d4
	moveq #90,%d2
	eor.l %d4,%d0
	mvz.b 269161706,%d1
	eor.l %d2,%d0
	mvz.b %d0,%d0
	cmp.l %d1,%d0
	jeq .L49
.L43:
	moveq #54,%d1
	lea tm_lock_text,%a0
	moveq #52,%d0
	move.b %d1,(%a0)+
.L45:
	clr.b %d3
	move.b %d0,(%a0)
	move.l #tm_lock_text,%d0
	move.b %d3,1(%a0)
	movem.l (%sp),#28
	lea (12,%sp),%sp
	rts
.L49:
	mvz.b 269161705,%d1
	moveq #10,%d4
	moveq #99,%d2
	move.l %d1,%d3
	remu.l %d4,%d0:%d3
	divu.l %d4,%d3
	move.l %d3,%a1
	add.l #48,%d0
	cmp.l %d1,%d2
	jcc .L44
	moveq #100,%d3
	divu.l %d3,%d1
	move.l %a1,%d2
	moveq #10,%d3
	remu.l %d3,%d4:%d2
	add.l #48,%d1
	move.b %d1,tm_lock_text
	lea tm_lock_text+1,%a0
	move.l %d4,%d1
	add.l #48,%d1
	move.b %d1,(%a0)+
	jra .L45
.L44:
	lea tm_lock_text,%a0
	moveq #9,%d2
	cmp.l %d1,%d2
	jcc .L45
	move.l %d3,%d1
	add.l #48,%d1
	move.b %d1,(%a0)+
	jra .L45
	.size	tm_get_lock, .-tm_get_lock
	.align	2
	.globl	tm_set_track
	.type	tm_set_track, @function
tm_set_track:
	move.l %d3,-(%sp)
	moveq #8,%d3
	move.l %d2,-(%sp)
	move.b 269161704,%d1
	move.b 269161705,%d0
	mvz.b %d1,%d2
	move.w %d0,%a0
	move.l 12(%sp),%d0
	cmp.l %d2,%d3
	jcs .L53
	move.w %a0,%d2
	tst.b %d2
	jlt .L53
	move.l %a0,%d3
	eor.l %d3,%d1
	moveq #90,%d3
	mvz.b 269161706,%d2
	eor.l %d3,%d1
	mvz.b %d1,%d1
	cmp.l %d2,%d1
	jeq .L61
.L53:
	moveq #64,%d2
.L52:
	move.b 269161704,%d1
	move.b 269161705,%d3
	move.w %d3,%a1
	mvz.b %d1,%d3
	move.l %d3,%a0
	moveq #8,%d3
	cmp.l %a0,%d3
	jcs .L55
	move.w %a1,%d3
	tst.b %d3
	jlt .L55
	move.l %a1,%d3
	eor.l %d3,%d1
	mvz.b 269161706,%d3
	move.l %d3,%a0
	moveq #90,%d3
	eor.l %d3,%d1
	mvz.b %d1,%d1
	cmp.l %a0,%d1
	jeq .L62
.L55:
	moveq #8,%d1
	cmp.l %d0,%d1
	jge .L57
	moveq #8,%d0
.L58:
	move.l %d0,%d1
	eor.l %d2,%d1
	move.b %d0,269161704
	move.b %d2,269161705
	moveq #90,%d2
	eor.l %d2,%d1
	move.b %d1,269161706
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	rts
.L57:
	tst.l %d0
	jge .L58
	clr.l %d0
	move.l %d0,%d1
	eor.l %d2,%d1
	move.b %d0,269161704
	move.b %d2,269161705
	moveq #90,%d2
	eor.l %d2,%d1
	move.b %d1,269161706
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	rts
.L61:
	move.b 269161705,%d2
	jra .L52
.L62:
	mvz.b 269161704,%d1
	add.l %d1,%d0
	jra .L55
	.size	tm_set_track, .-tm_set_track
	.align	2
	.globl	tm_set_lock
	.type	tm_set_lock, @function
tm_set_lock:
	move.l %d2,-(%sp)
	moveq #8,%d2
	move.b 269161704,%d0
	move.b 269161705,%d1
	move.w %d1,%a0
	mvz.b %d0,%d1
	cmp.l %d1,%d2
	jcs .L66
	move.w %a0,%d1
	tst.b %d1
	jlt .L66
	move.l %a0,%d2
	eor.l %d2,%d0
	moveq #90,%d2
	mvz.b 269161706,%d1
	eor.l %d2,%d0
	mvz.b %d0,%d0
	cmp.l %d1,%d0
	jeq .L74
.L66:
	moveq #64,%d0
.L65:
	add.l 8(%sp),%d0
	moveq #127,%d1
	cmp.l %d0,%d1
	jge .L67
	moveq #127,%d0
.L68:
	move.b 269161704,%d1
	move.b 269161705,%d2
	move.w %d2,%a1
	mvz.b %d1,%d2
	move.l %d2,%a0
	moveq #8,%d2
	cmp.l %a0,%d2
	jcs .L71
	move.w %a1,%d2
	tst.b %d2
	jlt .L71
	move.l %a1,%d2
	eor.l %d2,%d1
	mvz.b 269161706,%d2
	move.l %d2,%a0
	moveq #90,%d2
	eor.l %d2,%d1
	mvz.b %d1,%d1
	cmp.l %a0,%d1
	jeq .L75
.L71:
	sub.l %a0,%a0
	move.w %a0,%d2
	move.l %a0,%d1
	eor.l %d0,%d1
	move.b %d2,269161704
	move.b %d0,269161705
	moveq #90,%d0
	eor.l %d0,%d1
	move.b %d1,269161706
	move.l (%sp)+,%d2
	rts
.L67:
	tst.l %d0
	jge .L68
	clr.l %d0
	jra .L68
.L74:
	mvz.b 269161705,%d0
	jra .L65
.L75:
	move.b 269161704,%d1
	move.w %d1,%a0
	move.w %a0,%d2
	move.l %a0,%d1
	eor.l %d0,%d1
	move.b %d2,269161704
	move.b %d0,269161705
	moveq #90,%d0
	eor.l %d0,%d1
	move.b %d1,269161706
	move.l (%sp)+,%d2
	rts
	.size	tm_set_lock, .-tm_set_lock
	.local	tm_lock_text
	.comm	tm_lock_text,4,1
	.section	.rodata
	.type	tm_track_names, @object
	.size	tm_track_names, 36
tm_track_names:
	.string	"OFF"
	.string	"T1"
	.zero	1
	.string	"T2"
	.zero	1
	.string	"T3"
	.zero	1
	.string	"T4"
	.zero	1
	.string	"T5"
	.zero	1
	.string	"T6"
	.zero	1
	.string	"T7"
	.zero	1
	.string	"T8"
	.zero	1
	.globl	tm_label_lock
	.type	tm_label_lock, @object
	.size	tm_label_lock, 12
tm_label_lock:
	.string	"TURING LOCK"
	.globl	tm_label_track
	.type	tm_label_track, @object
	.size	tm_label_track, 13
tm_label_track:
	.string	"TURING TRACK"

| Appended to the generated turing.s by generate.py.
        .text
        .balign 4
        .global tm_note_hook

| The head of the stock MIDI-track chord loop (0x4009fb2e): d7 = track
| 0..7, d4 = chord slot 0..3, a2 -> the slot's resolved note byte. The
| displaced instructions load d0, d1 and d3 and the code after them reloads
| a0 and a1, so the C call may clobber d0-d1/a0-a1. The condition codes are
| set by the displaced moveq, as stock.
tm_note_hook:
        tst.l   %d4
        bne.s   1f
        move.l  %a2,-(%sp)
        move.l  %d7,-(%sp)
        jsr     tm_note
        addq.l  #8,%sp
1:      move.b  (%a2),%d1           | displaced
        mvs.b   %d1,%d0             | displaced
        moveq   #-1,%d3             | displaced
        jmp     0x4009fb34

| Explicitly initialized, loader-owned DRAM: a DRAM unit's .bss is never
| cleared. The C's static assertion checks the size.
        .balign 4
        .global tm_states
tm_states:
        .zero   64
